apiVersion: v1
kind: Namespace
metadata:
  name: kernexys-system
  labels:
    app.kubernetes.io/part-of: kernexys
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
