apiVersion: v1
kind: ServiceAccount
metadata:
  name: kernexys-control-api
  namespace: kernexys-system
  labels:
    app.kubernetes.io/name: kernexys-control-api
    app.kubernetes.io/part-of: kernexys
