apiVersion: batch/v1
kind: Job
metadata:
  name: kernexys-migrate
  namespace: kernexys-system
  labels:
    app: kernexys-migrate
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: kernexys-migrate
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: migrate
          image: kernexys/control-api:dev
          imagePullPolicy: IfNotPresent
          command: [alembic, upgrade, head]
          env:
            - name: KERNEXYS_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: kernexys-db
                  key: url
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: var-tmp
              mountPath: /var/tmp
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 16Mi
        - name: var-tmp
          emptyDir:
            sizeLimit: 16Mi
