{{- if and .Values.api.enabled .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name }}
  namespace: {{ .Values.namespace.system }}
  labels:
    app: kernexys-api
    {{- include "kernexys.labels" . | nindent 4 }}
{{- end }}
