apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kernexys-workers
resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - keda.yaml
commonLabels:
  component: inference-workers
